// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: orchestrator_private.proto

package grpc_private

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	OrderBy       *string                `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	Order         *string                `protobuf:"bytes,4,opt,name=order,proto3,oneof" json:"order,omitempty"`
	Search        *string                `protobuf:"bytes,5,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Os            *string                `protobuf:"bytes,7,opt,name=os,proto3,oneof" json:"os,omitempty"`
	Arch          *string                `protobuf:"bytes,8,opt,name=arch,proto3,oneof" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodesRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetNodesRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetNodesRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetNodesRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *GetNodesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetNodesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetNodesRequest) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *GetNodesRequest) GetArch() string {
	if x != nil && x.Arch != nil {
		return *x.Arch
	}
	return ""
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Node                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Query         *GetNodesRequest       `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_orchestrator_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodesResponse) GetResults() []*Node {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetNodesResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetNodesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetNodesResponse) GetQuery() *GetNodesRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_orchestrator_private_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SqlQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlQueryRequest) Reset() {
	*x = SqlQueryRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlQueryRequest) ProtoMessage() {}

func (x *SqlQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlQueryRequest.ProtoReflect.Descriptor instead.
func (*SqlQueryRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{3}
}

func (x *SqlQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SqlQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlQueryResponse) Reset() {
	*x = SqlQueryResponse{}
	mi := &file_orchestrator_private_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlQueryResponse) ProtoMessage() {}

func (x *SqlQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlQueryResponse.ProtoReflect.Descriptor instead.
func (*SqlQueryResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{4}
}

func (x *SqlQueryResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TriggerIngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIngestRequest) Reset() {
	*x = TriggerIngestRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIngestRequest) ProtoMessage() {}

func (x *TriggerIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIngestRequest.ProtoReflect.Descriptor instead.
func (*TriggerIngestRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{5}
}

type TriggerIngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerCount int32                  `protobuf:"varint,1,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerIngestResponse) Reset() {
	*x = TriggerIngestResponse{}
	mi := &file_orchestrator_private_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIngestResponse) ProtoMessage() {}

func (x *TriggerIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIngestResponse.ProtoReflect.Descriptor instead.
func (*TriggerIngestResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerIngestResponse) GetContainerCount() int32 {
	if x != nil {
		return x.ContainerCount
	}
	return 0
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DockerId      string                 `protobuf:"bytes,2,opt,name=docker_id,json=dockerId,proto3" json:"docker_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Uptime        int64                  `protobuf:"varint,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_orchestrator_private_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{7}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetDockerId() string {
	if x != nil {
		return x.DockerId
	}
	return ""
}

func (x *Container) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{8}
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_orchestrator_private_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{9}
}

func (x *ListContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type InitiateCloudRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCloudRegistrationRequest) Reset() {
	*x = InitiateCloudRegistrationRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCloudRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCloudRegistrationRequest) ProtoMessage() {}

func (x *InitiateCloudRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCloudRegistrationRequest.ProtoReflect.Descriptor instead.
func (*InitiateCloudRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{10}
}

func (x *InitiateCloudRegistrationRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *InitiateCloudRegistrationRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type InitiateCloudRegistrationResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserCode                string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUriComplete string                 `protobuf:"bytes,2,opt,name=verification_uri_complete,json=verificationUriComplete,proto3" json:"verification_uri_complete,omitempty"`
	ExpiresIn               int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Interval                int32                  `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InitiateCloudRegistrationResponse) Reset() {
	*x = InitiateCloudRegistrationResponse{}
	mi := &file_orchestrator_private_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCloudRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCloudRegistrationResponse) ProtoMessage() {}

func (x *InitiateCloudRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCloudRegistrationResponse.ProtoReflect.Descriptor instead.
func (*InitiateCloudRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{11}
}

func (x *InitiateCloudRegistrationResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *InitiateCloudRegistrationResponse) GetVerificationUriComplete() string {
	if x != nil {
		return x.VerificationUriComplete
	}
	return ""
}

func (x *InitiateCloudRegistrationResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *InitiateCloudRegistrationResponse) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type GetCloudRegistrationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudRegistrationStatusRequest) Reset() {
	*x = GetCloudRegistrationStatusRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudRegistrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudRegistrationStatusRequest) ProtoMessage() {}

func (x *GetCloudRegistrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudRegistrationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCloudRegistrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{12}
}

type GetCloudRegistrationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudRegistrationStatusResponse) Reset() {
	*x = GetCloudRegistrationStatusResponse{}
	mi := &file_orchestrator_private_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudRegistrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudRegistrationStatusResponse) ProtoMessage() {}

func (x *GetCloudRegistrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudRegistrationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCloudRegistrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{13}
}

func (x *GetCloudRegistrationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCloudRegistrationStatusResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type NewStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewStreamRequest) Reset() {
	*x = NewStreamRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewStreamRequest) ProtoMessage() {}

func (x *NewStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewStreamRequest.ProtoReflect.Descriptor instead.
func (*NewStreamRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{14}
}

func (x *NewStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NewStreamRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NewStreamRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CloseStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStreamRequest) Reset() {
	*x = CloseStreamRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStreamRequest) ProtoMessage() {}

func (x *CloseStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStreamRequest.ProtoReflect.Descriptor instead.
func (*CloseStreamRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{15}
}

func (x *CloseStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StreamState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamState) Reset() {
	*x = StreamState{}
	mi := &file_orchestrator_private_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamState) ProtoMessage() {}

func (x *StreamState) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamState.ProtoReflect.Descriptor instead.
func (*StreamState) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{16}
}

func (x *StreamState) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamState) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamState) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *StreamState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_orchestrator_private_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{17}
}

func (x *GetStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,8,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_orchestrator_private_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_private_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_orchestrator_private_proto_rawDescGZIP(), []int{18}
}

func (x *Stream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stream) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Stream) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stream) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Stream) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Stream) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Stream) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Stream) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

var File_orchestrator_private_proto protoreflect.FileDescriptor

const file_orchestrator_private_proto_rawDesc = "" +
	"\n" +
	"\x1aorchestrator_private.proto\x12\x17orchestrator.private.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb8\x02\n" +
	"\x0fGetNodesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x03H\x01R\x06offset\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x03 \x01(\tH\x02R\aorderBy\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x04 \x01(\tH\x03R\x05order\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x05 \x01(\tH\x04R\x06search\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x05R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\a \x01(\tH\x06R\x02os\x88\x01\x01\x12\x17\n" +
	"\x04arch\x18\b \x01(\tH\aR\x04arch\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\v\n" +
	"\t_order_byB\b\n" +
	"\x06_orderB\t\n" +
	"\a_searchB\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_osB\a\n" +
	"\x05_arch\"\xb7\x01\n" +
	"\x10GetNodesResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.orchestrator.private.v1.NodeR\aresults\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12>\n" +
	"\x05query\x18\x04 \x01(\v2(.orchestrator.private.v1.GetNodesRequestR\x05query\"*\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"'\n" +
	"\x0fSqlQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"*\n" +
	"\x10SqlQueryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x16\n" +
	"\x14TriggerIngestRequest\"@\n" +
	"\x15TriggerIngestResponse\x12'\n" +
	"\x0fcontainer_count\x18\x01 \x01(\x05R\x0econtainerCount\"\x97\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdocker_id\x18\x02 \x01(\tR\bdockerId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\x03R\x06uptime\"\x17\n" +
	"\x15ListContainersRequest\"\\\n" +
	"\x16ListContainersResponse\x12B\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\".orchestrator.private.v1.ContainerR\n" +
	"containers\"d\n" +
	" InitiateCloudRegistrationRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"\xb7\x01\n" +
	"!InitiateCloudRegistrationResponse\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12:\n" +
	"\x19verification_uri_complete\x18\x02 \x01(\tR\x17verificationUriComplete\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\x05R\binterval\"#\n" +
	"!GetCloudRegistrationStatusRequest\"[\n" +
	"\"GetCloudRegistrationStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"S\n" +
	"\x10NewStreamRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"1\n" +
	"\x12CloseStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"y\n" +
	"\vStreamState\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"/\n" +
	"\x10GetStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xcf\x01\n" +
	"\x06Stream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tclosed_at\x18\b \x01(\tR\bclosedAt2\xc1\b\n" +
	"\x13OrchestratorPrivate\x12_\n" +
	"\bGetNodes\x12(.orchestrator.private.v1.GetNodesRequest\x1a).orchestrator.private.v1.GetNodesResponse\x12_\n" +
	"\bSqlQuery\x12(.orchestrator.private.v1.SqlQueryRequest\x1a).orchestrator.private.v1.SqlQueryResponse\x12n\n" +
	"\rTriggerIngest\x12-.orchestrator.private.v1.TriggerIngestRequest\x1a..orchestrator.private.v1.TriggerIngestResponse\x12q\n" +
	"\x0eListContainers\x12..orchestrator.private.v1.ListContainersRequest\x1a/.orchestrator.private.v1.ListContainersResponse\x12\x92\x01\n" +
	"\x19InitiateCloudRegistration\x129.orchestrator.private.v1.InitiateCloudRegistrationRequest\x1a:.orchestrator.private.v1.InitiateCloudRegistrationResponse\x12W\n" +
	"\tNewStream\x12).orchestrator.private.v1.NewStreamRequest\x1a\x1f.orchestrator.private.v1.Stream\x12R\n" +
	"\vCloseStream\x12+.orchestrator.private.v1.CloseStreamRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\tGetStream\x12).orchestrator.private.v1.GetStreamRequest\x1a$.orchestrator.private.v1.StreamState\x12M\n" +
	"\vListStreams\x12\x16.google.protobuf.Empty\x1a$.orchestrator.private.v1.StreamState0\x01\x12\x95\x01\n" +
	"\x1aGetCloudRegistrationStatus\x12:.orchestrator.private.v1.GetCloudRegistrationStatusRequest\x1a;.orchestrator.private.v1.GetCloudRegistrationStatusResponseBWZUgithub.com/ambientlabscomputing/underleaf_v2/edge/orchestrator/interface/grpc_privateb\x06proto3"

var (
	file_orchestrator_private_proto_rawDescOnce sync.Once
	file_orchestrator_private_proto_rawDescData []byte
)

func file_orchestrator_private_proto_rawDescGZIP() []byte {
	file_orchestrator_private_proto_rawDescOnce.Do(func() {
		file_orchestrator_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_private_proto_rawDesc), len(file_orchestrator_private_proto_rawDesc)))
	})
	return file_orchestrator_private_proto_rawDescData
}

var file_orchestrator_private_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_orchestrator_private_proto_goTypes = []any{
	(*GetNodesRequest)(nil),                    // 0: orchestrator.private.v1.GetNodesRequest
	(*GetNodesResponse)(nil),                   // 1: orchestrator.private.v1.GetNodesResponse
	(*Node)(nil),                               // 2: orchestrator.private.v1.Node
	(*SqlQueryRequest)(nil),                    // 3: orchestrator.private.v1.SqlQueryRequest
	(*SqlQueryResponse)(nil),                   // 4: orchestrator.private.v1.SqlQueryResponse
	(*TriggerIngestRequest)(nil),               // 5: orchestrator.private.v1.TriggerIngestRequest
	(*TriggerIngestResponse)(nil),              // 6: orchestrator.private.v1.TriggerIngestResponse
	(*Container)(nil),                          // 7: orchestrator.private.v1.Container
	(*ListContainersRequest)(nil),              // 8: orchestrator.private.v1.ListContainersRequest
	(*ListContainersResponse)(nil),             // 9: orchestrator.private.v1.ListContainersResponse
	(*InitiateCloudRegistrationRequest)(nil),   // 10: orchestrator.private.v1.InitiateCloudRegistrationRequest
	(*InitiateCloudRegistrationResponse)(nil),  // 11: orchestrator.private.v1.InitiateCloudRegistrationResponse
	(*GetCloudRegistrationStatusRequest)(nil),  // 12: orchestrator.private.v1.GetCloudRegistrationStatusRequest
	(*GetCloudRegistrationStatusResponse)(nil), // 13: orchestrator.private.v1.GetCloudRegistrationStatusResponse
	(*NewStreamRequest)(nil),                   // 14: orchestrator.private.v1.NewStreamRequest
	(*CloseStreamRequest)(nil),                 // 15: orchestrator.private.v1.CloseStreamRequest
	(*StreamState)(nil),                        // 16: orchestrator.private.v1.StreamState
	(*GetStreamRequest)(nil),                   // 17: orchestrator.private.v1.GetStreamRequest
	(*Stream)(nil),                             // 18: orchestrator.private.v1.Stream
	(*emptypb.Empty)(nil),                      // 19: google.protobuf.Empty
}
var file_orchestrator_private_proto_depIdxs = []int32{
	2,  // 0: orchestrator.private.v1.GetNodesResponse.results:type_name -> orchestrator.private.v1.Node
	0,  // 1: orchestrator.private.v1.GetNodesResponse.query:type_name -> orchestrator.private.v1.GetNodesRequest
	7,  // 2: orchestrator.private.v1.ListContainersResponse.containers:type_name -> orchestrator.private.v1.Container
	0,  // 3: orchestrator.private.v1.OrchestratorPrivate.GetNodes:input_type -> orchestrator.private.v1.GetNodesRequest
	3,  // 4: orchestrator.private.v1.OrchestratorPrivate.SqlQuery:input_type -> orchestrator.private.v1.SqlQueryRequest
	5,  // 5: orchestrator.private.v1.OrchestratorPrivate.TriggerIngest:input_type -> orchestrator.private.v1.TriggerIngestRequest
	8,  // 6: orchestrator.private.v1.OrchestratorPrivate.ListContainers:input_type -> orchestrator.private.v1.ListContainersRequest
	10, // 7: orchestrator.private.v1.OrchestratorPrivate.InitiateCloudRegistration:input_type -> orchestrator.private.v1.InitiateCloudRegistrationRequest
	14, // 8: orchestrator.private.v1.OrchestratorPrivate.NewStream:input_type -> orchestrator.private.v1.NewStreamRequest
	15, // 9: orchestrator.private.v1.OrchestratorPrivate.CloseStream:input_type -> orchestrator.private.v1.CloseStreamRequest
	17, // 10: orchestrator.private.v1.OrchestratorPrivate.GetStream:input_type -> orchestrator.private.v1.GetStreamRequest
	19, // 11: orchestrator.private.v1.OrchestratorPrivate.ListStreams:input_type -> google.protobuf.Empty
	12, // 12: orchestrator.private.v1.OrchestratorPrivate.GetCloudRegistrationStatus:input_type -> orchestrator.private.v1.GetCloudRegistrationStatusRequest
	1,  // 13: orchestrator.private.v1.OrchestratorPrivate.GetNodes:output_type -> orchestrator.private.v1.GetNodesResponse
	4,  // 14: orchestrator.private.v1.OrchestratorPrivate.SqlQuery:output_type -> orchestrator.private.v1.SqlQueryResponse
	6,  // 15: orchestrator.private.v1.OrchestratorPrivate.TriggerIngest:output_type -> orchestrator.private.v1.TriggerIngestResponse
	9,  // 16: orchestrator.private.v1.OrchestratorPrivate.ListContainers:output_type -> orchestrator.private.v1.ListContainersResponse
	11, // 17: orchestrator.private.v1.OrchestratorPrivate.InitiateCloudRegistration:output_type -> orchestrator.private.v1.InitiateCloudRegistrationResponse
	18, // 18: orchestrator.private.v1.OrchestratorPrivate.NewStream:output_type -> orchestrator.private.v1.Stream
	19, // 19: orchestrator.private.v1.OrchestratorPrivate.CloseStream:output_type -> google.protobuf.Empty
	16, // 20: orchestrator.private.v1.OrchestratorPrivate.GetStream:output_type -> orchestrator.private.v1.StreamState
	16, // 21: orchestrator.private.v1.OrchestratorPrivate.ListStreams:output_type -> orchestrator.private.v1.StreamState
	13, // 22: orchestrator.private.v1.OrchestratorPrivate.GetCloudRegistrationStatus:output_type -> orchestrator.private.v1.GetCloudRegistrationStatusResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_orchestrator_private_proto_init() }
func file_orchestrator_private_proto_init() {
	if File_orchestrator_private_proto != nil {
		return
	}
	file_orchestrator_private_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_private_proto_rawDesc), len(file_orchestrator_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_private_proto_goTypes,
		DependencyIndexes: file_orchestrator_private_proto_depIdxs,
		MessageInfos:      file_orchestrator_private_proto_msgTypes,
	}.Build()
	File_orchestrator_private_proto = out.File
	file_orchestrator_private_proto_goTypes = nil
	file_orchestrator_private_proto_depIdxs = nil
}
