// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: orchestrator_private.proto

package grpc_private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorPrivate_GetNodes_FullMethodName                   = "/orchestrator.private.v1.OrchestratorPrivate/GetNodes"
	OrchestratorPrivate_SqlQuery_FullMethodName                   = "/orchestrator.private.v1.OrchestratorPrivate/SqlQuery"
	OrchestratorPrivate_TriggerIngest_FullMethodName              = "/orchestrator.private.v1.OrchestratorPrivate/TriggerIngest"
	OrchestratorPrivate_ListContainers_FullMethodName             = "/orchestrator.private.v1.OrchestratorPrivate/ListContainers"
	OrchestratorPrivate_InitiateCloudRegistration_FullMethodName  = "/orchestrator.private.v1.OrchestratorPrivate/InitiateCloudRegistration"
	OrchestratorPrivate_NewStream_FullMethodName                  = "/orchestrator.private.v1.OrchestratorPrivate/NewStream"
	OrchestratorPrivate_CloseStream_FullMethodName                = "/orchestrator.private.v1.OrchestratorPrivate/CloseStream"
	OrchestratorPrivate_GetStream_FullMethodName                  = "/orchestrator.private.v1.OrchestratorPrivate/GetStream"
	OrchestratorPrivate_ListStreams_FullMethodName                = "/orchestrator.private.v1.OrchestratorPrivate/ListStreams"
	OrchestratorPrivate_GetCloudRegistrationStatus_FullMethodName = "/orchestrator.private.v1.OrchestratorPrivate/GetCloudRegistrationStatus"
)

// OrchestratorPrivateClient is the client API for OrchestratorPrivate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorPrivate is the CLI-facing gRPC service, served over a unix socket.
type OrchestratorPrivateClient interface {
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	SqlQuery(ctx context.Context, in *SqlQueryRequest, opts ...grpc.CallOption) (*SqlQueryResponse, error)
	TriggerIngest(ctx context.Context, in *TriggerIngestRequest, opts ...grpc.CallOption) (*TriggerIngestResponse, error)
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	InitiateCloudRegistration(ctx context.Context, in *InitiateCloudRegistrationRequest, opts ...grpc.CallOption) (*InitiateCloudRegistrationResponse, error)
	NewStream(ctx context.Context, in *NewStreamRequest, opts ...grpc.CallOption) (*Stream, error)
	CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*StreamState, error)
	ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamState], error)
	GetCloudRegistrationStatus(ctx context.Context, in *GetCloudRegistrationStatusRequest, opts ...grpc.CallOption) (*GetCloudRegistrationStatusResponse, error)
}

type orchestratorPrivateClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorPrivateClient(cc grpc.ClientConnInterface) OrchestratorPrivateClient {
	return &orchestratorPrivateClient{cc}
}

func (c *orchestratorPrivateClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) SqlQuery(ctx context.Context, in *SqlQueryRequest, opts ...grpc.CallOption) (*SqlQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlQueryResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_SqlQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) TriggerIngest(ctx context.Context, in *TriggerIngestRequest, opts ...grpc.CallOption) (*TriggerIngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerIngestResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_TriggerIngest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) InitiateCloudRegistration(ctx context.Context, in *InitiateCloudRegistrationRequest, opts ...grpc.CallOption) (*InitiateCloudRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateCloudRegistrationResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_InitiateCloudRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) NewStream(ctx context.Context, in *NewStreamRequest, opts ...grpc.CallOption) (*Stream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stream)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_NewStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_CloseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*StreamState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamState)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPrivateClient) ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorPrivate_ServiceDesc.Streams[0], OrchestratorPrivate_ListStreams_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, StreamState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorPrivate_ListStreamsClient = grpc.ServerStreamingClient[StreamState]

func (c *orchestratorPrivateClient) GetCloudRegistrationStatus(ctx context.Context, in *GetCloudRegistrationStatusRequest, opts ...grpc.CallOption) (*GetCloudRegistrationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCloudRegistrationStatusResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_GetCloudRegistrationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorPrivateServer is the server API for OrchestratorPrivate service.
// All implementations must embed UnimplementedOrchestratorPrivateServer
// for forward compatibility.
//
// OrchestratorPrivate is the CLI-facing gRPC service, served over a unix socket.
type OrchestratorPrivateServer interface {
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	SqlQuery(context.Context, *SqlQueryRequest) (*SqlQueryResponse, error)
	TriggerIngest(context.Context, *TriggerIngestRequest) (*TriggerIngestResponse, error)
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	InitiateCloudRegistration(context.Context, *InitiateCloudRegistrationRequest) (*InitiateCloudRegistrationResponse, error)
	NewStream(context.Context, *NewStreamRequest) (*Stream, error)
	CloseStream(context.Context, *CloseStreamRequest) (*emptypb.Empty, error)
	GetStream(context.Context, *GetStreamRequest) (*StreamState, error)
	ListStreams(*emptypb.Empty, grpc.ServerStreamingServer[StreamState]) error
	GetCloudRegistrationStatus(context.Context, *GetCloudRegistrationStatusRequest) (*GetCloudRegistrationStatusResponse, error)
	mustEmbedUnimplementedOrchestratorPrivateServer()
}

// UnimplementedOrchestratorPrivateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorPrivateServer struct{}

func (UnimplementedOrchestratorPrivateServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedOrchestratorPrivateServer) SqlQuery(context.Context, *SqlQueryRequest) (*SqlQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SqlQuery not implemented")
}
func (UnimplementedOrchestratorPrivateServer) TriggerIngest(context.Context, *TriggerIngestRequest) (*TriggerIngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerIngest not implemented")
}
func (UnimplementedOrchestratorPrivateServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedOrchestratorPrivateServer) InitiateCloudRegistration(context.Context, *InitiateCloudRegistrationRequest) (*InitiateCloudRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateCloudRegistration not implemented")
}
func (UnimplementedOrchestratorPrivateServer) NewStream(context.Context, *NewStreamRequest) (*Stream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewStream not implemented")
}
func (UnimplementedOrchestratorPrivateServer) CloseStream(context.Context, *CloseStreamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseStream not implemented")
}
func (UnimplementedOrchestratorPrivateServer) GetStream(context.Context, *GetStreamRequest) (*StreamState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedOrchestratorPrivateServer) ListStreams(*emptypb.Empty, grpc.ServerStreamingServer[StreamState]) error {
	return status.Errorf(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedOrchestratorPrivateServer) GetCloudRegistrationStatus(context.Context, *GetCloudRegistrationStatusRequest) (*GetCloudRegistrationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCloudRegistrationStatus not implemented")
}
func (UnimplementedOrchestratorPrivateServer) mustEmbedUnimplementedOrchestratorPrivateServer() {}
func (UnimplementedOrchestratorPrivateServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorPrivateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorPrivateServer will
// result in compilation errors.
type UnsafeOrchestratorPrivateServer interface {
	mustEmbedUnimplementedOrchestratorPrivateServer()
}

func RegisterOrchestratorPrivateServer(s grpc.ServiceRegistrar, srv OrchestratorPrivateServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorPrivateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorPrivate_ServiceDesc, srv)
}

func _OrchestratorPrivate_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_SqlQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).SqlQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_SqlQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).SqlQuery(ctx, req.(*SqlQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_TriggerIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).TriggerIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_TriggerIngest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).TriggerIngest(ctx, req.(*TriggerIngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_InitiateCloudRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateCloudRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).InitiateCloudRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_InitiateCloudRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).InitiateCloudRegistration(ctx, req.(*InitiateCloudRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_NewStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).NewStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_NewStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).NewStream(ctx, req.(*NewStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_CloseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).CloseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_CloseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).CloseStream(ctx, req.(*CloseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPrivate_ListStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorPrivateServer).ListStreams(m, &grpc.GenericServerStream[emptypb.Empty, StreamState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorPrivate_ListStreamsServer = grpc.ServerStreamingServer[StreamState]

func _OrchestratorPrivate_GetCloudRegistrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudRegistrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).GetCloudRegistrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_GetCloudRegistrationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).GetCloudRegistrationStatus(ctx, req.(*GetCloudRegistrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorPrivate_ServiceDesc is the grpc.ServiceDesc for OrchestratorPrivate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorPrivate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.private.v1.OrchestratorPrivate",
	HandlerType: (*OrchestratorPrivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _OrchestratorPrivate_GetNodes_Handler,
		},
		{
			MethodName: "SqlQuery",
			Handler:    _OrchestratorPrivate_SqlQuery_Handler,
		},
		{
			MethodName: "TriggerIngest",
			Handler:    _OrchestratorPrivate_TriggerIngest_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _OrchestratorPrivate_ListContainers_Handler,
		},
		{
			MethodName: "InitiateCloudRegistration",
			Handler:    _OrchestratorPrivate_InitiateCloudRegistration_Handler,
		},
		{
			MethodName: "NewStream",
			Handler:    _OrchestratorPrivate_NewStream_Handler,
		},
		{
			MethodName: "CloseStream",
			Handler:    _OrchestratorPrivate_CloseStream_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _OrchestratorPrivate_GetStream_Handler,
		},
		{
			MethodName: "GetCloudRegistrationStatus",
			Handler:    _OrchestratorPrivate_GetCloudRegistrationStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStreams",
			Handler:       _OrchestratorPrivate_ListStreams_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator_private.proto",
}
