// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: interface/grpc_private/orchestrator_private.proto

package grpc_private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorPrivate_GetNodes_FullMethodName = "/orchestrator.private.v1.OrchestratorPrivate/GetNodes"
)

// OrchestratorPrivateClient is the client API for OrchestratorPrivate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorPrivate is the CLI-facing gRPC service, served over a unix socket.
type OrchestratorPrivateClient interface {
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
}

type orchestratorPrivateClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorPrivateClient(cc grpc.ClientConnInterface) OrchestratorPrivateClient {
	return &orchestratorPrivateClient{cc}
}

func (c *orchestratorPrivateClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, OrchestratorPrivate_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorPrivateServer is the server API for OrchestratorPrivate service.
// All implementations must embed UnimplementedOrchestratorPrivateServer
// for forward compatibility.
//
// OrchestratorPrivate is the CLI-facing gRPC service, served over a unix socket.
type OrchestratorPrivateServer interface {
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	mustEmbedUnimplementedOrchestratorPrivateServer()
}

// UnimplementedOrchestratorPrivateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorPrivateServer struct{}

func (UnimplementedOrchestratorPrivateServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedOrchestratorPrivateServer) mustEmbedUnimplementedOrchestratorPrivateServer() {}
func (UnimplementedOrchestratorPrivateServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorPrivateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorPrivateServer will
// result in compilation errors.
type UnsafeOrchestratorPrivateServer interface {
	mustEmbedUnimplementedOrchestratorPrivateServer()
}

func RegisterOrchestratorPrivateServer(s grpc.ServiceRegistrar, srv OrchestratorPrivateServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorPrivateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorPrivate_ServiceDesc, srv)
}

func _OrchestratorPrivate_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPrivateServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPrivate_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPrivateServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorPrivate_ServiceDesc is the grpc.ServiceDesc for OrchestratorPrivate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorPrivate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.private.v1.OrchestratorPrivate",
	HandlerType: (*OrchestratorPrivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _OrchestratorPrivate_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface/grpc_private/orchestrator_private.proto",
}
