"""first migration

Revision ID: 09441847ab0e
Revises:
Create Date: 2026-06-30 18:18:24.523673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09441847ab0e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS underleaf")

    # principal_accounts has no dependencies — create first
    op.create_table(
        "principal_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    # clusters references principal_accounts; manager_node_id FK added after nodes exists
    op.create_table(
        "clusters",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=False),
        sa.Column("manager_node_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_account_id"],
            ["underleaf.principal_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "nodes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["underleaf.clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    # Now that nodes exists, add the FK from clusters.manager_node_id -> nodes.id
    op.create_foreign_key(
        "fk_clusters_manager_node_id_nodes",
        "clusters",
        "nodes",
        ["manager_node_id"],
        ["id"],
        source_schema="underleaf",
        referent_schema="underleaf",
    )
    op.create_table(
        "billing_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column(
            "stripe_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_account_id"],
            ["underleaf.principal_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "cluster_candidates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_code", sa.String(), nullable=False),
        sa.Column("device_code_hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("proposed_cluster_name", sa.String(), nullable=False),
        sa.Column("proposed_cluster_id", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=True),
        sa.Column("cluster_id", sa.String(), nullable=True),
        sa.Column("node_id", sa.String(), nullable=True),
        sa.Column("one_time_token_hash", sa.String(), nullable=True),
        sa.Column(
            "one_time_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("device_code_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("poll_interval", sa.Integer(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["underleaf.clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["underleaf.nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_code_hash"),
        sa.UniqueConstraint("user_code"),
        schema="underleaf",
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["underleaf.nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_account_id"],
            ["underleaf.principal_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "entitlements_buckets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("billing_account_id", sa.String(), nullable=False),
        sa.Column("network_traffic_balance", sa.Integer(), nullable=False),
        sa.Column("connection_slot_balance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_account_id"],
            ["underleaf.billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "streams",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["underleaf.connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("billing_account_id", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_account_id"],
            ["underleaf.billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "usage_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("billing_account_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("usage_unit", sa.String(), nullable=False),
        sa.Column("usage_amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_account_id"],
            ["underleaf.billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "user_passwords",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["underleaf.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_passwords", schema="underleaf")
    op.drop_table("usage_events", schema="underleaf")
    op.drop_table("subscriptions", schema="underleaf")
    op.drop_table("streams", schema="underleaf")
    op.drop_table("entitlements_buckets", schema="underleaf")
    op.drop_table("users", schema="underleaf")
    op.drop_table("connections", schema="underleaf")
    op.drop_table("cluster_candidates", schema="underleaf")
    op.drop_table("billing_accounts", schema="underleaf")
    # Drop the deferred FK before dropping nodes/clusters
    op.drop_constraint(
        "fk_clusters_manager_node_id_nodes",
        "clusters",
        schema="underleaf",
        type_="foreignkey",
    )
    op.drop_table("nodes", schema="underleaf")
    op.drop_table("clusters", schema="underleaf")
    op.drop_table("principal_accounts", schema="underleaf")
    op.execute("DROP SCHEMA IF EXISTS underleaf")
    # ### end Alembic commands ###
