"""first revision

Revision ID: 89ca30dc3bb0
Revises:
Create Date: 2026-06-18 19:42:31.696145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = "89ca30dc3bb0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS underleaf")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "principal_accounts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "billing_accounts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_data", JSONB(), nullable=False, server_default="{}"),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_account_id"],
            ["underleaf.principal_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "clusters",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_account_id"],
            ["underleaf.principal_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("principal_account_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_account_id"],
            ["underleaf.principal_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "user_passwords",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["underleaf.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "entitlements_buckets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("billing_account_id", sa.String(), nullable=False),
        sa.Column("network_traffic_balance", sa.Integer(), nullable=False),
        sa.Column("connection_slot_balance", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_account_id"],
            ["underleaf.billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "nodes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["underleaf.clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "subscriptions",
        sa.Column("billing_account_id", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_account_id"],
            ["underleaf.billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "usage_events",
        sa.Column("billing_account_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("usage_unit", sa.String(), nullable=False),
        sa.Column("usage_amount", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_account_id"],
            ["underleaf.billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "tunnels",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["underleaf.nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    op.create_table(
        "connections",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tunnel_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tunnel_id"],
            ["underleaf.tunnels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="underleaf",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connections", schema="underleaf")
    op.drop_table("tunnels", schema="underleaf")
    op.drop_table("usage_events", schema="underleaf")
    op.drop_table("subscriptions", schema="underleaf")
    op.drop_table("nodes", schema="underleaf")
    op.drop_table("entitlements_buckets", schema="underleaf")
    op.drop_table("user_passwords", schema="underleaf")
    op.drop_table("users", schema="underleaf")
    op.drop_table("clusters", schema="underleaf")
    op.drop_table("billing_accounts", schema="underleaf")
    op.drop_table("principal_accounts", schema="underleaf")
    op.execute("DROP SCHEMA IF EXISTS underleaf")
    # ### end Alembic commands ###
