# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import conn_worker_pb2 as conn__worker__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conn_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConnectionWorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConnection = channel.unary_unary(
                '/conn_worker.ConnectionWorker/CreateConnection',
                request_serializer=conn__worker__pb2.CreateConnectionRequest.SerializeToString,
                response_deserializer=conn__worker__pb2.Connection.FromString,
                _registered_method=True)
        self.GetConnection = channel.unary_unary(
                '/conn_worker.ConnectionWorker/GetConnection',
                request_serializer=conn__worker__pb2.GetConnectionRequest.SerializeToString,
                response_deserializer=conn__worker__pb2.Connection.FromString,
                _registered_method=True)
        self.TerminateConnection = channel.unary_unary(
                '/conn_worker.ConnectionWorker/TerminateConnection',
                request_serializer=conn__worker__pb2.TerminateConnectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListConnections = channel.unary_stream(
                '/conn_worker.ConnectionWorker/ListConnections',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=conn__worker__pb2.Connection.FromString,
                _registered_method=True)
        self.NewStream = channel.unary_unary(
                '/conn_worker.ConnectionWorker/NewStream',
                request_serializer=conn__worker__pb2.NewStreamRequest.SerializeToString,
                response_deserializer=conn__worker__pb2.Stream.FromString,
                _registered_method=True)
        self.CloseStream = channel.unary_unary(
                '/conn_worker.ConnectionWorker/CloseStream',
                request_serializer=conn__worker__pb2.CloseStreamRequest.SerializeToString,
                response_deserializer=conn__worker__pb2.CloseStreamResponse.FromString,
                _registered_method=True)
        self.ListStreams = channel.unary_stream(
                '/conn_worker.ConnectionWorker/ListStreams',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=conn__worker__pb2.Stream.FromString,
                _registered_method=True)
        self.GetStream = channel.unary_unary(
                '/conn_worker.ConnectionWorker/GetStream',
                request_serializer=conn__worker__pb2.GetStreamRequest.SerializeToString,
                response_deserializer=conn__worker__pb2.Stream.FromString,
                _registered_method=True)


class ConnectionWorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateConnection(self, request, context):
        """Connections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewStream(self, request, context):
        """Streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStreams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConnection,
                    request_deserializer=conn__worker__pb2.CreateConnectionRequest.FromString,
                    response_serializer=conn__worker__pb2.Connection.SerializeToString,
            ),
            'GetConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnection,
                    request_deserializer=conn__worker__pb2.GetConnectionRequest.FromString,
                    response_serializer=conn__worker__pb2.Connection.SerializeToString,
            ),
            'TerminateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateConnection,
                    request_deserializer=conn__worker__pb2.TerminateConnectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListConnections': grpc.unary_stream_rpc_method_handler(
                    servicer.ListConnections,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=conn__worker__pb2.Connection.SerializeToString,
            ),
            'NewStream': grpc.unary_unary_rpc_method_handler(
                    servicer.NewStream,
                    request_deserializer=conn__worker__pb2.NewStreamRequest.FromString,
                    response_serializer=conn__worker__pb2.Stream.SerializeToString,
            ),
            'CloseStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseStream,
                    request_deserializer=conn__worker__pb2.CloseStreamRequest.FromString,
                    response_serializer=conn__worker__pb2.CloseStreamResponse.SerializeToString,
            ),
            'ListStreams': grpc.unary_stream_rpc_method_handler(
                    servicer.ListStreams,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=conn__worker__pb2.Stream.SerializeToString,
            ),
            'GetStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=conn__worker__pb2.GetStreamRequest.FromString,
                    response_serializer=conn__worker__pb2.Stream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conn_worker.ConnectionWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conn_worker.ConnectionWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectionWorker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conn_worker.ConnectionWorker/CreateConnection',
            conn__worker__pb2.CreateConnectionRequest.SerializeToString,
            conn__worker__pb2.Connection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conn_worker.ConnectionWorker/GetConnection',
            conn__worker__pb2.GetConnectionRequest.SerializeToString,
            conn__worker__pb2.Connection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conn_worker.ConnectionWorker/TerminateConnection',
            conn__worker__pb2.TerminateConnectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/conn_worker.ConnectionWorker/ListConnections',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            conn__worker__pb2.Connection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conn_worker.ConnectionWorker/NewStream',
            conn__worker__pb2.NewStreamRequest.SerializeToString,
            conn__worker__pb2.Stream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conn_worker.ConnectionWorker/CloseStream',
            conn__worker__pb2.CloseStreamRequest.SerializeToString,
            conn__worker__pb2.CloseStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStreams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/conn_worker.ConnectionWorker/ListStreams',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            conn__worker__pb2.Stream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conn_worker.ConnectionWorker/GetStream',
            conn__worker__pb2.GetStreamRequest.SerializeToString,
            conn__worker__pb2.Stream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
