// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent_private.proto

package grpc_private

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_agent_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_agent_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_private_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent's own ping result
	AgentStatus      string `protobuf:"bytes,1,opt,name=agent_status,json=agentStatus,proto3" json:"agent_status,omitempty"`
	AgentTimestampMs int64  `protobuf:"varint,2,opt,name=agent_timestamp_ms,json=agentTimestampMs,proto3" json:"agent_timestamp_ms,omitempty"`
	// Result from the agent pinging the orchestrator
	OrchestratorReachable   bool   `protobuf:"varint,3,opt,name=orchestrator_reachable,json=orchestratorReachable,proto3" json:"orchestrator_reachable,omitempty"`
	OrchestratorResponder   string `protobuf:"bytes,4,opt,name=orchestrator_responder,json=orchestratorResponder,proto3" json:"orchestrator_responder,omitempty"`
	OrchestratorTimestampMs int64  `protobuf:"varint,5,opt,name=orchestrator_timestamp_ms,json=orchestratorTimestampMs,proto3" json:"orchestrator_timestamp_ms,omitempty"`
	OrchestratorError       string `protobuf:"bytes,6,opt,name=orchestrator_error,json=orchestratorError,proto3" json:"orchestrator_error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_agent_private_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetAgentStatus() string {
	if x != nil {
		return x.AgentStatus
	}
	return ""
}

func (x *PingResponse) GetAgentTimestampMs() int64 {
	if x != nil {
		return x.AgentTimestampMs
	}
	return 0
}

func (x *PingResponse) GetOrchestratorReachable() bool {
	if x != nil {
		return x.OrchestratorReachable
	}
	return false
}

func (x *PingResponse) GetOrchestratorResponder() string {
	if x != nil {
		return x.OrchestratorResponder
	}
	return ""
}

func (x *PingResponse) GetOrchestratorTimestampMs() int64 {
	if x != nil {
		return x.OrchestratorTimestampMs
	}
	return 0
}

func (x *PingResponse) GetOrchestratorError() string {
	if x != nil {
		return x.OrchestratorError
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_private_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{4}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_agent_private_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{5}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_private_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_private_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_agent_private_proto protoreflect.FileDescriptor

const file_agent_private_proto_rawDesc = "" +
	"\n" +
	"\x13agent_private.proto\x12\x10agent.private.v1\"\x12\n" +
	"\x10GetStatusRequest\"+\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\r\n" +
	"\vPingRequest\"\xb8\x02\n" +
	"\fPingResponse\x12!\n" +
	"\fagent_status\x18\x01 \x01(\tR\vagentStatus\x12,\n" +
	"\x12agent_timestamp_ms\x18\x02 \x01(\x03R\x10agentTimestampMs\x125\n" +
	"\x16orchestrator_reachable\x18\x03 \x01(\bR\x15orchestratorReachable\x125\n" +
	"\x16orchestrator_responder\x18\x04 \x01(\tR\x15orchestratorResponder\x12:\n" +
	"\x19orchestrator_timestamp_ms\x18\x05 \x01(\x03R\x17orchestratorTimestampMs\x12-\n" +
	"\x12orchestrator_error\x18\x06 \x01(\tR\x11orchestratorError\"\x11\n" +
	"\x0fRegisterRequest\"*\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"V\n" +
	"\x10RegisterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12*\n" +
	"\x04node\x18\x02 \x01(\v2\x16.agent.private.v1.NodeR\x04node2\xfe\x01\n" +
	"\fAgentPrivate\x12T\n" +
	"\tGetStatus\x12\".agent.private.v1.GetStatusRequest\x1a#.agent.private.v1.GetStatusResponse\x12E\n" +
	"\x04Ping\x12\x1d.agent.private.v1.PingRequest\x1a\x1e.agent.private.v1.PingResponse\x12Q\n" +
	"\bRegister\x12!.agent.private.v1.RegisterRequest\x1a\".agent.private.v1.RegisterResponseBPZNgithub.com/ambientlabscomputing/underleaf_v2/edge/agent/interface/grpc_privateb\x06proto3"

var (
	file_agent_private_proto_rawDescOnce sync.Once
	file_agent_private_proto_rawDescData []byte
)

func file_agent_private_proto_rawDescGZIP() []byte {
	file_agent_private_proto_rawDescOnce.Do(func() {
		file_agent_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_private_proto_rawDesc), len(file_agent_private_proto_rawDesc)))
	})
	return file_agent_private_proto_rawDescData
}

var file_agent_private_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_private_proto_goTypes = []any{
	(*GetStatusRequest)(nil),  // 0: agent.private.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: agent.private.v1.GetStatusResponse
	(*PingRequest)(nil),       // 2: agent.private.v1.PingRequest
	(*PingResponse)(nil),      // 3: agent.private.v1.PingResponse
	(*RegisterRequest)(nil),   // 4: agent.private.v1.RegisterRequest
	(*Node)(nil),              // 5: agent.private.v1.Node
	(*RegisterResponse)(nil),  // 6: agent.private.v1.RegisterResponse
}
var file_agent_private_proto_depIdxs = []int32{
	5, // 0: agent.private.v1.RegisterResponse.node:type_name -> agent.private.v1.Node
	0, // 1: agent.private.v1.AgentPrivate.GetStatus:input_type -> agent.private.v1.GetStatusRequest
	2, // 2: agent.private.v1.AgentPrivate.Ping:input_type -> agent.private.v1.PingRequest
	4, // 3: agent.private.v1.AgentPrivate.Register:input_type -> agent.private.v1.RegisterRequest
	1, // 4: agent.private.v1.AgentPrivate.GetStatus:output_type -> agent.private.v1.GetStatusResponse
	3, // 5: agent.private.v1.AgentPrivate.Ping:output_type -> agent.private.v1.PingResponse
	6, // 6: agent.private.v1.AgentPrivate.Register:output_type -> agent.private.v1.RegisterResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_private_proto_init() }
func file_agent_private_proto_init() {
	if File_agent_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_private_proto_rawDesc), len(file_agent_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_private_proto_goTypes,
		DependencyIndexes: file_agent_private_proto_depIdxs,
		MessageInfos:      file_agent_private_proto_msgTypes,
	}.Build()
	File_agent_private_proto = out.File
	file_agent_private_proto_goTypes = nil
	file_agent_private_proto_depIdxs = nil
}
