// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent/interface/grpc_private/agent_private.proto

package grpc_private

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_agent_interface_grpc_private_agent_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_interface_grpc_private_agent_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_interface_grpc_private_agent_private_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_agent_interface_grpc_private_agent_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_interface_grpc_private_agent_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_interface_grpc_private_agent_private_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_agent_interface_grpc_private_agent_private_proto protoreflect.FileDescriptor

const file_agent_interface_grpc_private_agent_private_proto_rawDesc = "" +
	"\n" +
	"0agent/interface/grpc_private/agent_private.proto\x12\x10agent.private.v1\"\x12\n" +
	"\x10GetStatusRequest\"+\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2d\n" +
	"\fAgentPrivate\x12T\n" +
	"\tGetStatus\x12\".agent.private.v1.GetStatusRequest\x1a#.agent.private.v1.GetStatusResponseBPZNgithub.com/ambientlabscomputing/underleaf_v2/edge/agent/interface/grpc_privateb\x06proto3"

var (
	file_agent_interface_grpc_private_agent_private_proto_rawDescOnce sync.Once
	file_agent_interface_grpc_private_agent_private_proto_rawDescData []byte
)

func file_agent_interface_grpc_private_agent_private_proto_rawDescGZIP() []byte {
	file_agent_interface_grpc_private_agent_private_proto_rawDescOnce.Do(func() {
		file_agent_interface_grpc_private_agent_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_interface_grpc_private_agent_private_proto_rawDesc), len(file_agent_interface_grpc_private_agent_private_proto_rawDesc)))
	})
	return file_agent_interface_grpc_private_agent_private_proto_rawDescData
}

var file_agent_interface_grpc_private_agent_private_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_interface_grpc_private_agent_private_proto_goTypes = []any{
	(*GetStatusRequest)(nil),  // 0: agent.private.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: agent.private.v1.GetStatusResponse
}
var file_agent_interface_grpc_private_agent_private_proto_depIdxs = []int32{
	0, // 0: agent.private.v1.AgentPrivate.GetStatus:input_type -> agent.private.v1.GetStatusRequest
	1, // 1: agent.private.v1.AgentPrivate.GetStatus:output_type -> agent.private.v1.GetStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_interface_grpc_private_agent_private_proto_init() }
func file_agent_interface_grpc_private_agent_private_proto_init() {
	if File_agent_interface_grpc_private_agent_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_interface_grpc_private_agent_private_proto_rawDesc), len(file_agent_interface_grpc_private_agent_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_interface_grpc_private_agent_private_proto_goTypes,
		DependencyIndexes: file_agent_interface_grpc_private_agent_private_proto_depIdxs,
		MessageInfos:      file_agent_interface_grpc_private_agent_private_proto_msgTypes,
	}.Build()
	File_agent_interface_grpc_private_agent_private_proto = out.File
	file_agent_interface_grpc_private_agent_private_proto_goTypes = nil
	file_agent_interface_grpc_private_agent_private_proto_depIdxs = nil
}
