// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: conn_worker.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectionRequest) Reset() {
	*x = CreateConnectionRequest{}
	mi := &file_conn_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectionRequest) ProtoMessage() {}

func (x *CreateConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectionRequest.ProtoReflect.Descriptor instead.
func (*CreateConnectionRequest) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConnectionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateConnectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,7,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_conn_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Connection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connection) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Connection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Connection) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Connection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Connection) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Connection) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

type GetConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionRequest) Reset() {
	*x = GetConnectionRequest{}
	mi := &file_conn_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionRequest) ProtoMessage() {}

func (x *GetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TerminateConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateConnectionRequest) Reset() {
	*x = TerminateConnectionRequest{}
	mi := &file_conn_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateConnectionRequest) ProtoMessage() {}

func (x *TerminateConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateConnectionRequest.ProtoReflect.Descriptor instead.
func (*TerminateConnectionRequest) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewStreamRequest) Reset() {
	*x = NewStreamRequest{}
	mi := &file_conn_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewStreamRequest) ProtoMessage() {}

func (x *NewStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewStreamRequest.ProtoReflect.Descriptor instead.
func (*NewStreamRequest) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{4}
}

func (x *NewStreamRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *NewStreamRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NewStreamRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NewStreamRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Port          int32                  `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,9,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_conn_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{5}
}

func (x *Stream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stream) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Stream) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stream) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Stream) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Stream) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Stream) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Stream) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Stream) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

type GetStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_conn_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{6}
}

func (x *GetStreamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloseStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStreamRequest) Reset() {
	*x = CloseStreamRequest{}
	mi := &file_conn_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStreamRequest) ProtoMessage() {}

func (x *CloseStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStreamRequest.ProtoReflect.Descriptor instead.
func (*CloseStreamRequest) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{7}
}

func (x *CloseStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type CloseStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStreamResponse) Reset() {
	*x = CloseStreamResponse{}
	mi := &file_conn_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStreamResponse) ProtoMessage() {}

func (x *CloseStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conn_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStreamResponse.ProtoReflect.Descriptor instead.
func (*CloseStreamResponse) Descriptor() ([]byte, []int) {
	return file_conn_worker_proto_rawDescGZIP(), []int{8}
}

func (x *CloseStreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloseStreamResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_conn_worker_proto protoreflect.FileDescriptor

const file_conn_worker_proto_rawDesc = "" +
	"\n" +
	"\x11conn_worker.proto\x12\vconn_worker\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\x17CreateConnectionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb3\x01\n" +
	"\n" +
	"Connection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tclosed_at\x18\a \x01(\tR\bclosedAt\"&\n" +
	"\x14GetConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x1aTerminateConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x10NewStreamRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"\xeb\x01\n" +
	"\x06Stream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04port\x18\a \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tclosed_at\x18\t \x01(\tR\bclosedAt\"\"\n" +
	"\x10GetStreamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x12CloseStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"=\n" +
	"\x13CloseStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xe2\x04\n" +
	"\x10ConnectionWorker\x12Q\n" +
	"\x10CreateConnection\x12$.conn_worker.CreateConnectionRequest\x1a\x17.conn_worker.Connection\x12K\n" +
	"\rGetConnection\x12!.conn_worker.GetConnectionRequest\x1a\x17.conn_worker.Connection\x12V\n" +
	"\x13TerminateConnection\x12'.conn_worker.TerminateConnectionRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x0fListConnections\x12\x16.google.protobuf.Empty\x1a\x17.conn_worker.Connection0\x01\x12?\n" +
	"\tNewStream\x12\x1d.conn_worker.NewStreamRequest\x1a\x13.conn_worker.Stream\x12P\n" +
	"\vCloseStream\x12\x1f.conn_worker.CloseStreamRequest\x1a .conn_worker.CloseStreamResponse\x12<\n" +
	"\vListStreams\x12\x16.google.protobuf.Empty\x1a\x13.conn_worker.Stream0\x01\x12?\n" +
	"\tGetStream\x12\x1d.conn_worker.GetStreamRequest\x1a\x13.conn_worker.StreamBOZMgithub.com/ambientlabscomputing/underleaf_v2/cloud/conn_worker/interface/grpcb\x06proto3"

var (
	file_conn_worker_proto_rawDescOnce sync.Once
	file_conn_worker_proto_rawDescData []byte
)

func file_conn_worker_proto_rawDescGZIP() []byte {
	file_conn_worker_proto_rawDescOnce.Do(func() {
		file_conn_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conn_worker_proto_rawDesc), len(file_conn_worker_proto_rawDesc)))
	})
	return file_conn_worker_proto_rawDescData
}

var file_conn_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_conn_worker_proto_goTypes = []any{
	(*CreateConnectionRequest)(nil),    // 0: conn_worker.CreateConnectionRequest
	(*Connection)(nil),                 // 1: conn_worker.Connection
	(*GetConnectionRequest)(nil),       // 2: conn_worker.GetConnectionRequest
	(*TerminateConnectionRequest)(nil), // 3: conn_worker.TerminateConnectionRequest
	(*NewStreamRequest)(nil),           // 4: conn_worker.NewStreamRequest
	(*Stream)(nil),                     // 5: conn_worker.Stream
	(*GetStreamRequest)(nil),           // 6: conn_worker.GetStreamRequest
	(*CloseStreamRequest)(nil),         // 7: conn_worker.CloseStreamRequest
	(*CloseStreamResponse)(nil),        // 8: conn_worker.CloseStreamResponse
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_conn_worker_proto_depIdxs = []int32{
	0, // 0: conn_worker.ConnectionWorker.CreateConnection:input_type -> conn_worker.CreateConnectionRequest
	2, // 1: conn_worker.ConnectionWorker.GetConnection:input_type -> conn_worker.GetConnectionRequest
	3, // 2: conn_worker.ConnectionWorker.TerminateConnection:input_type -> conn_worker.TerminateConnectionRequest
	9, // 3: conn_worker.ConnectionWorker.ListConnections:input_type -> google.protobuf.Empty
	4, // 4: conn_worker.ConnectionWorker.NewStream:input_type -> conn_worker.NewStreamRequest
	7, // 5: conn_worker.ConnectionWorker.CloseStream:input_type -> conn_worker.CloseStreamRequest
	9, // 6: conn_worker.ConnectionWorker.ListStreams:input_type -> google.protobuf.Empty
	6, // 7: conn_worker.ConnectionWorker.GetStream:input_type -> conn_worker.GetStreamRequest
	1, // 8: conn_worker.ConnectionWorker.CreateConnection:output_type -> conn_worker.Connection
	1, // 9: conn_worker.ConnectionWorker.GetConnection:output_type -> conn_worker.Connection
	9, // 10: conn_worker.ConnectionWorker.TerminateConnection:output_type -> google.protobuf.Empty
	1, // 11: conn_worker.ConnectionWorker.ListConnections:output_type -> conn_worker.Connection
	5, // 12: conn_worker.ConnectionWorker.NewStream:output_type -> conn_worker.Stream
	8, // 13: conn_worker.ConnectionWorker.CloseStream:output_type -> conn_worker.CloseStreamResponse
	5, // 14: conn_worker.ConnectionWorker.ListStreams:output_type -> conn_worker.Stream
	5, // 15: conn_worker.ConnectionWorker.GetStream:output_type -> conn_worker.Stream
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conn_worker_proto_init() }
func file_conn_worker_proto_init() {
	if File_conn_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conn_worker_proto_rawDesc), len(file_conn_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conn_worker_proto_goTypes,
		DependencyIndexes: file_conn_worker_proto_depIdxs,
		MessageInfos:      file_conn_worker_proto_msgTypes,
	}.Build()
	File_conn_worker_proto = out.File
	file_conn_worker_proto_goTypes = nil
	file_conn_worker_proto_depIdxs = nil
}
