// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: conn_worker.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionWorker_CreateConnection_FullMethodName    = "/conn_worker.ConnectionWorker/CreateConnection"
	ConnectionWorker_GetConnection_FullMethodName       = "/conn_worker.ConnectionWorker/GetConnection"
	ConnectionWorker_TerminateConnection_FullMethodName = "/conn_worker.ConnectionWorker/TerminateConnection"
	ConnectionWorker_ListConnections_FullMethodName     = "/conn_worker.ConnectionWorker/ListConnections"
	ConnectionWorker_NewStream_FullMethodName           = "/conn_worker.ConnectionWorker/NewStream"
	ConnectionWorker_CloseStream_FullMethodName         = "/conn_worker.ConnectionWorker/CloseStream"
	ConnectionWorker_ListStreams_FullMethodName         = "/conn_worker.ConnectionWorker/ListStreams"
	ConnectionWorker_GetStream_FullMethodName           = "/conn_worker.ConnectionWorker/GetStream"
)

// ConnectionWorkerClient is the client API for ConnectionWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionWorkerClient interface {
	// Connections
	CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*Connection, error)
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*Connection, error)
	TerminateConnection(ctx context.Context, in *TerminateConnectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Connection], error)
	// Streams
	NewStream(ctx context.Context, in *NewStreamRequest, opts ...grpc.CallOption) (*Stream, error)
	CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*CloseStreamResponse, error)
	ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Stream], error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*Stream, error)
}

type connectionWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionWorkerClient(cc grpc.ClientConnInterface) ConnectionWorkerClient {
	return &connectionWorkerClient{cc}
}

func (c *connectionWorkerClient) CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, ConnectionWorker_CreateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionWorkerClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, ConnectionWorker_GetConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionWorkerClient) TerminateConnection(ctx context.Context, in *TerminateConnectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConnectionWorker_TerminateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionWorkerClient) ListConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Connection], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionWorker_ServiceDesc.Streams[0], ConnectionWorker_ListConnections_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Connection]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionWorker_ListConnectionsClient = grpc.ServerStreamingClient[Connection]

func (c *connectionWorkerClient) NewStream(ctx context.Context, in *NewStreamRequest, opts ...grpc.CallOption) (*Stream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stream)
	err := c.cc.Invoke(ctx, ConnectionWorker_NewStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionWorkerClient) CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*CloseStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseStreamResponse)
	err := c.cc.Invoke(ctx, ConnectionWorker_CloseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionWorkerClient) ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Stream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionWorker_ServiceDesc.Streams[1], ConnectionWorker_ListStreams_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Stream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionWorker_ListStreamsClient = grpc.ServerStreamingClient[Stream]

func (c *connectionWorkerClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*Stream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stream)
	err := c.cc.Invoke(ctx, ConnectionWorker_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionWorkerServer is the server API for ConnectionWorker service.
// All implementations must embed UnimplementedConnectionWorkerServer
// for forward compatibility.
type ConnectionWorkerServer interface {
	// Connections
	CreateConnection(context.Context, *CreateConnectionRequest) (*Connection, error)
	GetConnection(context.Context, *GetConnectionRequest) (*Connection, error)
	TerminateConnection(context.Context, *TerminateConnectionRequest) (*emptypb.Empty, error)
	ListConnections(*emptypb.Empty, grpc.ServerStreamingServer[Connection]) error
	// Streams
	NewStream(context.Context, *NewStreamRequest) (*Stream, error)
	CloseStream(context.Context, *CloseStreamRequest) (*CloseStreamResponse, error)
	ListStreams(*emptypb.Empty, grpc.ServerStreamingServer[Stream]) error
	GetStream(context.Context, *GetStreamRequest) (*Stream, error)
	mustEmbedUnimplementedConnectionWorkerServer()
}

// UnimplementedConnectionWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionWorkerServer struct{}

func (UnimplementedConnectionWorkerServer) CreateConnection(context.Context, *CreateConnectionRequest) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConnection not implemented")
}
func (UnimplementedConnectionWorkerServer) GetConnection(context.Context, *GetConnectionRequest) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedConnectionWorkerServer) TerminateConnection(context.Context, *TerminateConnectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateConnection not implemented")
}
func (UnimplementedConnectionWorkerServer) ListConnections(*emptypb.Empty, grpc.ServerStreamingServer[Connection]) error {
	return status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedConnectionWorkerServer) NewStream(context.Context, *NewStreamRequest) (*Stream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewStream not implemented")
}
func (UnimplementedConnectionWorkerServer) CloseStream(context.Context, *CloseStreamRequest) (*CloseStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseStream not implemented")
}
func (UnimplementedConnectionWorkerServer) ListStreams(*emptypb.Empty, grpc.ServerStreamingServer[Stream]) error {
	return status.Errorf(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedConnectionWorkerServer) GetStream(context.Context, *GetStreamRequest) (*Stream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedConnectionWorkerServer) mustEmbedUnimplementedConnectionWorkerServer() {}
func (UnimplementedConnectionWorkerServer) testEmbeddedByValue()                          {}

// UnsafeConnectionWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionWorkerServer will
// result in compilation errors.
type UnsafeConnectionWorkerServer interface {
	mustEmbedUnimplementedConnectionWorkerServer()
}

func RegisterConnectionWorkerServer(s grpc.ServiceRegistrar, srv ConnectionWorkerServer) {
	// If the following call pancis, it indicates UnimplementedConnectionWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionWorker_ServiceDesc, srv)
}

func _ConnectionWorker_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionWorkerServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionWorker_CreateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionWorkerServer).CreateConnection(ctx, req.(*CreateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionWorker_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionWorkerServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionWorker_GetConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionWorkerServer).GetConnection(ctx, req.(*GetConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionWorker_TerminateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionWorkerServer).TerminateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionWorker_TerminateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionWorkerServer).TerminateConnection(ctx, req.(*TerminateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionWorker_ListConnections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectionWorkerServer).ListConnections(m, &grpc.GenericServerStream[emptypb.Empty, Connection]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionWorker_ListConnectionsServer = grpc.ServerStreamingServer[Connection]

func _ConnectionWorker_NewStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionWorkerServer).NewStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionWorker_NewStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionWorkerServer).NewStream(ctx, req.(*NewStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionWorker_CloseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionWorkerServer).CloseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionWorker_CloseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionWorkerServer).CloseStream(ctx, req.(*CloseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionWorker_ListStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectionWorkerServer).ListStreams(m, &grpc.GenericServerStream[emptypb.Empty, Stream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionWorker_ListStreamsServer = grpc.ServerStreamingServer[Stream]

func _ConnectionWorker_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionWorkerServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionWorker_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionWorkerServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionWorker_ServiceDesc is the grpc.ServiceDesc for ConnectionWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conn_worker.ConnectionWorker",
	HandlerType: (*ConnectionWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConnection",
			Handler:    _ConnectionWorker_CreateConnection_Handler,
		},
		{
			MethodName: "GetConnection",
			Handler:    _ConnectionWorker_GetConnection_Handler,
		},
		{
			MethodName: "TerminateConnection",
			Handler:    _ConnectionWorker_TerminateConnection_Handler,
		},
		{
			MethodName: "NewStream",
			Handler:    _ConnectionWorker_NewStream_Handler,
		},
		{
			MethodName: "CloseStream",
			Handler:    _ConnectionWorker_CloseStream_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _ConnectionWorker_GetStream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListConnections",
			Handler:       _ConnectionWorker_ListConnections_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListStreams",
			Handler:       _ConnectionWorker_ListStreams_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "conn_worker.proto",
}
