gateway:
    gateway_port: 9020
    node_connections_port: 9021
    read_timeout: "5s"
    write_timeout: "10s"
    idle_timeout: "15s"
    domain: "underleaf.local"
redis:
    host: "redis"
    port: 6379
    password: ""
    db: 0
    ttl_seconds: 86400
