// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agent_public.proto

package grpc_public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentPublic_GetStatus_FullMethodName           = "/agent.public.v1.AgentPublic/GetStatus"
	AgentPublic_Ping_FullMethodName                = "/agent.public.v1.AgentPublic/Ping"
	AgentPublic_IngestContainers_FullMethodName    = "/agent.public.v1.AgentPublic/IngestContainers"
	AgentPublic_GetNode_FullMethodName             = "/agent.public.v1.AgentPublic/GetNode"
	AgentPublic_NewStream_FullMethodName           = "/agent.public.v1.AgentPublic/NewStream"
	AgentPublic_CloseStream_FullMethodName         = "/agent.public.v1.AgentPublic/CloseStream"
	AgentPublic_GetStream_FullMethodName           = "/agent.public.v1.AgentPublic/GetStream"
	AgentPublic_ListStreams_FullMethodName         = "/agent.public.v1.AgentPublic/ListStreams"
	AgentPublic_GetContainerLogs_FullMethodName    = "/agent.public.v1.AgentPublic/GetContainerLogs"
	AgentPublic_StreamContainerLogs_FullMethodName = "/agent.public.v1.AgentPublic/StreamContainerLogs"
	AgentPublic_CreateVolume_FullMethodName        = "/agent.public.v1.AgentPublic/CreateVolume"
	AgentPublic_ListVolumes_FullMethodName         = "/agent.public.v1.AgentPublic/ListVolumes"
	AgentPublic_CreateContainer_FullMethodName     = "/agent.public.v1.AgentPublic/CreateContainer"
	AgentPublic_StartContainer_FullMethodName      = "/agent.public.v1.AgentPublic/StartContainer"
	AgentPublic_StopContainer_FullMethodName       = "/agent.public.v1.AgentPublic/StopContainer"
	AgentPublic_RemoveContainer_FullMethodName     = "/agent.public.v1.AgentPublic/RemoveContainer"
)

// AgentPublicClient is the client API for AgentPublic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentPublic is the orchestrator/agent-facing gRPC service, served over TCP.
type AgentPublicClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	IngestContainers(ctx context.Context, in *IngestContainersRequest, opts ...grpc.CallOption) (*IngestContainersResponse, error)
	GetNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Node, error)
	// Stream RPCs
	NewStream(ctx context.Context, in *NewStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*StreamState, error)
	ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamState], error)
	// Log RPCs — agent is the source of truth for container logs.
	GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error)
	StreamContainerLogs(ctx context.Context, in *StreamContainerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	// Deployment lifecycle RPCs — orchestrator-initiated container/volume
	// management. The orchestrator owns naming/identity decisions (names are
	// already namespaced by the time they reach the agent); the agent is a
	// thin, stateless-per-call Docker executor. Responses are accept/error
	// only — a pull or build can take tens of seconds, so these don't block
	// on it. Final state surfaces through the existing ReportContainers push.
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	StartContainer(ctx context.Context, in *ContainerNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopContainer(ctx context.Context, in *ContainerNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveContainer(ctx context.Context, in *ContainerNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type agentPublicClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentPublicClient(cc grpc.ClientConnInterface) AgentPublicClient {
	return &agentPublicClient{cc}
}

func (c *agentPublicClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AgentPublic_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentPublic_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) IngestContainers(ctx context.Context, in *IngestContainersRequest, opts ...grpc.CallOption) (*IngestContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestContainersResponse)
	err := c.cc.Invoke(ctx, AgentPublic_IngestContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) GetNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, AgentPublic_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) NewStream(ctx context.Context, in *NewStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentPublic_NewStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentPublic_CloseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*StreamState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamState)
	err := c.cc.Invoke(ctx, AgentPublic_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentPublic_ServiceDesc.Streams[0], AgentPublic_ListStreams_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, StreamState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentPublic_ListStreamsClient = grpc.ServerStreamingClient[StreamState]

func (c *agentPublicClient) GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerLogsResponse)
	err := c.cc.Invoke(ctx, AgentPublic_GetContainerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) StreamContainerLogs(ctx context.Context, in *StreamContainerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentPublic_ServiceDesc.Streams[1], AgentPublic_StreamContainerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamContainerLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentPublic_StreamContainerLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *agentPublicClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, AgentPublic_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, AgentPublic_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContainerResponse)
	err := c.cc.Invoke(ctx, AgentPublic_CreateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) StartContainer(ctx context.Context, in *ContainerNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentPublic_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) StopContainer(ctx context.Context, in *ContainerNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentPublic_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPublicClient) RemoveContainer(ctx context.Context, in *ContainerNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentPublic_RemoveContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentPublicServer is the server API for AgentPublic service.
// All implementations must embed UnimplementedAgentPublicServer
// for forward compatibility.
//
// AgentPublic is the orchestrator/agent-facing gRPC service, served over TCP.
type AgentPublicServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	IngestContainers(context.Context, *IngestContainersRequest) (*IngestContainersResponse, error)
	GetNode(context.Context, *emptypb.Empty) (*Node, error)
	// Stream RPCs
	NewStream(context.Context, *NewStreamRequest) (*emptypb.Empty, error)
	CloseStream(context.Context, *CloseStreamRequest) (*emptypb.Empty, error)
	GetStream(context.Context, *GetStreamRequest) (*StreamState, error)
	ListStreams(*emptypb.Empty, grpc.ServerStreamingServer[StreamState]) error
	// Log RPCs — agent is the source of truth for container logs.
	GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error)
	StreamContainerLogs(*StreamContainerLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	// Deployment lifecycle RPCs — orchestrator-initiated container/volume
	// management. The orchestrator owns naming/identity decisions (names are
	// already namespaced by the time they reach the agent); the agent is a
	// thin, stateless-per-call Docker executor. Responses are accept/error
	// only — a pull or build can take tens of seconds, so these don't block
	// on it. Final state surfaces through the existing ReportContainers push.
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	StartContainer(context.Context, *ContainerNameRequest) (*emptypb.Empty, error)
	StopContainer(context.Context, *ContainerNameRequest) (*emptypb.Empty, error)
	RemoveContainer(context.Context, *ContainerNameRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAgentPublicServer()
}

// UnimplementedAgentPublicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentPublicServer struct{}

func (UnimplementedAgentPublicServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAgentPublicServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentPublicServer) IngestContainers(context.Context, *IngestContainersRequest) (*IngestContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestContainers not implemented")
}
func (UnimplementedAgentPublicServer) GetNode(context.Context, *emptypb.Empty) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedAgentPublicServer) NewStream(context.Context, *NewStreamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewStream not implemented")
}
func (UnimplementedAgentPublicServer) CloseStream(context.Context, *CloseStreamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseStream not implemented")
}
func (UnimplementedAgentPublicServer) GetStream(context.Context, *GetStreamRequest) (*StreamState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedAgentPublicServer) ListStreams(*emptypb.Empty, grpc.ServerStreamingServer[StreamState]) error {
	return status.Errorf(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedAgentPublicServer) GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainerLogs not implemented")
}
func (UnimplementedAgentPublicServer) StreamContainerLogs(*StreamContainerLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Errorf(codes.Unimplemented, "method StreamContainerLogs not implemented")
}
func (UnimplementedAgentPublicServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedAgentPublicServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedAgentPublicServer) CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}
func (UnimplementedAgentPublicServer) StartContainer(context.Context, *ContainerNameRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedAgentPublicServer) StopContainer(context.Context, *ContainerNameRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedAgentPublicServer) RemoveContainer(context.Context, *ContainerNameRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContainer not implemented")
}
func (UnimplementedAgentPublicServer) mustEmbedUnimplementedAgentPublicServer() {}
func (UnimplementedAgentPublicServer) testEmbeddedByValue()                     {}

// UnsafeAgentPublicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentPublicServer will
// result in compilation errors.
type UnsafeAgentPublicServer interface {
	mustEmbedUnimplementedAgentPublicServer()
}

func RegisterAgentPublicServer(s grpc.ServiceRegistrar, srv AgentPublicServer) {
	// If the following call pancis, it indicates UnimplementedAgentPublicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentPublic_ServiceDesc, srv)
}

func _AgentPublic_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_IngestContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).IngestContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_IngestContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).IngestContainers(ctx, req.(*IngestContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).GetNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_NewStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).NewStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_NewStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).NewStream(ctx, req.(*NewStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_CloseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).CloseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_CloseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).CloseStream(ctx, req.(*CloseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_ListStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentPublicServer).ListStreams(m, &grpc.GenericServerStream[emptypb.Empty, StreamState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentPublic_ListStreamsServer = grpc.ServerStreamingServer[StreamState]

func _AgentPublic_GetContainerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).GetContainerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_GetContainerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).GetContainerLogs(ctx, req.(*GetContainerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_StreamContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamContainerLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentPublicServer).StreamContainerLogs(m, &grpc.GenericServerStream[StreamContainerLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentPublic_StreamContainerLogsServer = grpc.ServerStreamingServer[LogLine]

func _AgentPublic_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_CreateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).StartContainer(ctx, req.(*ContainerNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).StopContainer(ctx, req.(*ContainerNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPublic_RemoveContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).RemoveContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_RemoveContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).RemoveContainer(ctx, req.(*ContainerNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentPublic_ServiceDesc is the grpc.ServiceDesc for AgentPublic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentPublic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.public.v1.AgentPublic",
	HandlerType: (*AgentPublicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _AgentPublic_GetStatus_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AgentPublic_Ping_Handler,
		},
		{
			MethodName: "IngestContainers",
			Handler:    _AgentPublic_IngestContainers_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _AgentPublic_GetNode_Handler,
		},
		{
			MethodName: "NewStream",
			Handler:    _AgentPublic_NewStream_Handler,
		},
		{
			MethodName: "CloseStream",
			Handler:    _AgentPublic_CloseStream_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _AgentPublic_GetStream_Handler,
		},
		{
			MethodName: "GetContainerLogs",
			Handler:    _AgentPublic_GetContainerLogs_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _AgentPublic_CreateVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _AgentPublic_ListVolumes_Handler,
		},
		{
			MethodName: "CreateContainer",
			Handler:    _AgentPublic_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _AgentPublic_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _AgentPublic_StopContainer_Handler,
		},
		{
			MethodName: "RemoveContainer",
			Handler:    _AgentPublic_RemoveContainer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStreams",
			Handler:       _AgentPublic_ListStreams_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamContainerLogs",
			Handler:       _AgentPublic_StreamContainerLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent_public.proto",
}
