// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agent/interface/grpc_public/agent_public.proto

package grpc_public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentPublic_GetStatus_FullMethodName = "/agent.public.v1.AgentPublic/GetStatus"
)

// AgentPublicClient is the client API for AgentPublic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentPublic is the orchestrator/agent-facing gRPC service, served over TCP.
type AgentPublicClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type agentPublicClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentPublicClient(cc grpc.ClientConnInterface) AgentPublicClient {
	return &agentPublicClient{cc}
}

func (c *agentPublicClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AgentPublic_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentPublicServer is the server API for AgentPublic service.
// All implementations must embed UnimplementedAgentPublicServer
// for forward compatibility.
//
// AgentPublic is the orchestrator/agent-facing gRPC service, served over TCP.
type AgentPublicServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedAgentPublicServer()
}

// UnimplementedAgentPublicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentPublicServer struct{}

func (UnimplementedAgentPublicServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAgentPublicServer) mustEmbedUnimplementedAgentPublicServer() {}
func (UnimplementedAgentPublicServer) testEmbeddedByValue()                     {}

// UnsafeAgentPublicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentPublicServer will
// result in compilation errors.
type UnsafeAgentPublicServer interface {
	mustEmbedUnimplementedAgentPublicServer()
}

func RegisterAgentPublicServer(s grpc.ServiceRegistrar, srv AgentPublicServer) {
	// If the following call pancis, it indicates UnimplementedAgentPublicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentPublic_ServiceDesc, srv)
}

func _AgentPublic_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPublicServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPublic_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPublicServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentPublic_ServiceDesc is the grpc.ServiceDesc for AgentPublic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentPublic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.public.v1.AgentPublic",
	HandlerType: (*AgentPublicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _AgentPublic_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/interface/grpc_public/agent_public.proto",
}
