// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: orchestrator_public.proto

package grpc_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{0}
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_orchestrator_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PingRequest) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Responder       string                 `protobuf:"bytes,1,opt,name=responder,proto3" json:"responder,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetResponder() string {
	if x != nil {
		return x.Responder
	}
	return ""
}

func (x *PingResponse) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateNodeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_orchestrator_public_proto protoreflect.FileDescriptor

const file_orchestrator_public_proto_rawDesc = "" +
	"\n" +
	"\x19orchestrator_public.proto\x12\x16orchestrator.public.v1\"\x11\n" +
	"\x0fGetNodesRequest\"F\n" +
	"\x10GetNodesResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.orchestrator.public.v1.NodeR\x05nodes\"*\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Q\n" +
	"\vPingRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\"X\n" +
	"\fPingResponse\x12\x1c\n" +
	"\tresponder\x18\x01 \x01(\tR\tresponder\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\"'\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x12CreateNodeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xab\x02\n" +
	"\x12OrchestratorPublic\x12c\n" +
	"\n" +
	"CreateNode\x12).orchestrator.public.v1.CreateNodeRequest\x1a*.orchestrator.public.v1.CreateNodeResponse\x12]\n" +
	"\bGetNodes\x12'.orchestrator.public.v1.GetNodesRequest\x1a(.orchestrator.public.v1.GetNodesResponse\x12Q\n" +
	"\x04Ping\x12#.orchestrator.public.v1.PingRequest\x1a$.orchestrator.public.v1.PingResponseBVZTgithub.com/ambientlabscomputing/underleaf_v2/edge/orchestrator/interface/grpc_publicb\x06proto3"

var (
	file_orchestrator_public_proto_rawDescOnce sync.Once
	file_orchestrator_public_proto_rawDescData []byte
)

func file_orchestrator_public_proto_rawDescGZIP() []byte {
	file_orchestrator_public_proto_rawDescOnce.Do(func() {
		file_orchestrator_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_public_proto_rawDesc), len(file_orchestrator_public_proto_rawDesc)))
	})
	return file_orchestrator_public_proto_rawDescData
}

var file_orchestrator_public_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_orchestrator_public_proto_goTypes = []any{
	(*GetNodesRequest)(nil),    // 0: orchestrator.public.v1.GetNodesRequest
	(*GetNodesResponse)(nil),   // 1: orchestrator.public.v1.GetNodesResponse
	(*Node)(nil),               // 2: orchestrator.public.v1.Node
	(*PingRequest)(nil),        // 3: orchestrator.public.v1.PingRequest
	(*PingResponse)(nil),       // 4: orchestrator.public.v1.PingResponse
	(*CreateNodeRequest)(nil),  // 5: orchestrator.public.v1.CreateNodeRequest
	(*CreateNodeResponse)(nil), // 6: orchestrator.public.v1.CreateNodeResponse
}
var file_orchestrator_public_proto_depIdxs = []int32{
	2, // 0: orchestrator.public.v1.GetNodesResponse.nodes:type_name -> orchestrator.public.v1.Node
	5, // 1: orchestrator.public.v1.OrchestratorPublic.CreateNode:input_type -> orchestrator.public.v1.CreateNodeRequest
	0, // 2: orchestrator.public.v1.OrchestratorPublic.GetNodes:input_type -> orchestrator.public.v1.GetNodesRequest
	3, // 3: orchestrator.public.v1.OrchestratorPublic.Ping:input_type -> orchestrator.public.v1.PingRequest
	6, // 4: orchestrator.public.v1.OrchestratorPublic.CreateNode:output_type -> orchestrator.public.v1.CreateNodeResponse
	1, // 5: orchestrator.public.v1.OrchestratorPublic.GetNodes:output_type -> orchestrator.public.v1.GetNodesResponse
	4, // 6: orchestrator.public.v1.OrchestratorPublic.Ping:output_type -> orchestrator.public.v1.PingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orchestrator_public_proto_init() }
func file_orchestrator_public_proto_init() {
	if File_orchestrator_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_public_proto_rawDesc), len(file_orchestrator_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_public_proto_goTypes,
		DependencyIndexes: file_orchestrator_public_proto_depIdxs,
		MessageInfos:      file_orchestrator_public_proto_msgTypes,
	}.Build()
	File_orchestrator_public_proto = out.File
	file_orchestrator_public_proto_goTypes = nil
	file_orchestrator_public_proto_depIdxs = nil
}
