// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: orchestrator_public.proto

package grpc_public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	OrderBy       *string                `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	Order         *string                `protobuf:"bytes,4,opt,name=order,proto3,oneof" json:"order,omitempty"`
	Search        *string                `protobuf:"bytes,5,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Os            *string                `protobuf:"bytes,7,opt,name=os,proto3,oneof" json:"os,omitempty"`
	Arch          *string                `protobuf:"bytes,8,opt,name=arch,proto3,oneof" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodesRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetNodesRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetNodesRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetNodesRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *GetNodesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetNodesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetNodesRequest) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *GetNodesRequest) GetArch() string {
	if x != nil && x.Arch != nil {
		return *x.Arch
	}
	return ""
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Node                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Query         *GetNodesRequest       `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodesResponse) GetResults() []*Node {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetNodesResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetNodesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetNodesResponse) GetQuery() *GetNodesRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_orchestrator_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Node) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Node) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type PingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PingRequest) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Responder       string                 `protobuf:"bytes,1,opt,name=responder,proto3" json:"responder,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetResponder() string {
	if x != nil {
		return x.Responder
	}
	return ""
}

func (x *PingResponse) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateNodeRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CreateNodeRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateNodeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateNodeResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CreateNodeResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DockerId      string                 `protobuf:"bytes,2,opt,name=docker_id,json=dockerId,proto3" json:"docker_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Uptime        int64                  `protobuf:"varint,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_orchestrator_public_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{7}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetDockerId() string {
	if x != nil {
		return x.DockerId
	}
	return ""
}

func (x *Container) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type ReportContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Containers    []*Container           `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContainersRequest) Reset() {
	*x = ReportContainersRequest{}
	mi := &file_orchestrator_public_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContainersRequest) ProtoMessage() {}

func (x *ReportContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContainersRequest.ProtoReflect.Descriptor instead.
func (*ReportContainersRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{8}
}

func (x *ReportContainersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportContainersRequest) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ReportContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContainersResponse) Reset() {
	*x = ReportContainersResponse{}
	mi := &file_orchestrator_public_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContainersResponse) ProtoMessage() {}

func (x *ReportContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_public_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContainersResponse.ProtoReflect.Descriptor instead.
func (*ReportContainersResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_public_proto_rawDescGZIP(), []int{9}
}

func (x *ReportContainersResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_orchestrator_public_proto protoreflect.FileDescriptor

const file_orchestrator_public_proto_rawDesc = "" +
	"\n" +
	"\x19orchestrator_public.proto\x12\x16orchestrator.public.v1\"\xb8\x02\n" +
	"\x0fGetNodesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x03H\x01R\x06offset\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x03 \x01(\tH\x02R\aorderBy\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x04 \x01(\tH\x03R\x05order\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x05 \x01(\tH\x04R\x06search\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x05R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\a \x01(\tH\x06R\x02os\x88\x01\x01\x12\x17\n" +
	"\x04arch\x18\b \x01(\tH\aR\x04arch\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\v\n" +
	"\t_order_byB\b\n" +
	"\x06_orderB\t\n" +
	"\a_searchB\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_osB\a\n" +
	"\x05_arch\"\xb5\x01\n" +
	"\x10GetNodesResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.orchestrator.public.v1.NodeR\aresults\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12=\n" +
	"\x05query\x18\x04 \x01(\v2'.orchestrator.public.v1.GetNodesRequestR\x05query\"m\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\"Q\n" +
	"\vPingRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\"X\n" +
	"\fPingResponse\x12\x1c\n" +
	"\tresponder\x18\x01 \x01(\tR\tresponder\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\"j\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"{\n" +
	"\x12CreateNodeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\"\x97\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdocker_id\x18\x02 \x01(\tR\bdockerId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\x03R\x06uptime\"u\n" +
	"\x17ReportContainersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12A\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2!.orchestrator.public.v1.ContainerR\n" +
	"containers\"6\n" +
	"\x18ReportContainersResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted2\xa2\x03\n" +
	"\x12OrchestratorPublic\x12c\n" +
	"\n" +
	"CreateNode\x12).orchestrator.public.v1.CreateNodeRequest\x1a*.orchestrator.public.v1.CreateNodeResponse\x12]\n" +
	"\bGetNodes\x12'.orchestrator.public.v1.GetNodesRequest\x1a(.orchestrator.public.v1.GetNodesResponse\x12Q\n" +
	"\x04Ping\x12#.orchestrator.public.v1.PingRequest\x1a$.orchestrator.public.v1.PingResponse\x12u\n" +
	"\x10ReportContainers\x12/.orchestrator.public.v1.ReportContainersRequest\x1a0.orchestrator.public.v1.ReportContainersResponseBVZTgithub.com/ambientlabscomputing/underleaf_v2/edge/orchestrator/interface/grpc_publicb\x06proto3"

var (
	file_orchestrator_public_proto_rawDescOnce sync.Once
	file_orchestrator_public_proto_rawDescData []byte
)

func file_orchestrator_public_proto_rawDescGZIP() []byte {
	file_orchestrator_public_proto_rawDescOnce.Do(func() {
		file_orchestrator_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_public_proto_rawDesc), len(file_orchestrator_public_proto_rawDesc)))
	})
	return file_orchestrator_public_proto_rawDescData
}

var file_orchestrator_public_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_orchestrator_public_proto_goTypes = []any{
	(*GetNodesRequest)(nil),          // 0: orchestrator.public.v1.GetNodesRequest
	(*GetNodesResponse)(nil),         // 1: orchestrator.public.v1.GetNodesResponse
	(*Node)(nil),                     // 2: orchestrator.public.v1.Node
	(*PingRequest)(nil),              // 3: orchestrator.public.v1.PingRequest
	(*PingResponse)(nil),             // 4: orchestrator.public.v1.PingResponse
	(*CreateNodeRequest)(nil),        // 5: orchestrator.public.v1.CreateNodeRequest
	(*CreateNodeResponse)(nil),       // 6: orchestrator.public.v1.CreateNodeResponse
	(*Container)(nil),                // 7: orchestrator.public.v1.Container
	(*ReportContainersRequest)(nil),  // 8: orchestrator.public.v1.ReportContainersRequest
	(*ReportContainersResponse)(nil), // 9: orchestrator.public.v1.ReportContainersResponse
}
var file_orchestrator_public_proto_depIdxs = []int32{
	2, // 0: orchestrator.public.v1.GetNodesResponse.results:type_name -> orchestrator.public.v1.Node
	0, // 1: orchestrator.public.v1.GetNodesResponse.query:type_name -> orchestrator.public.v1.GetNodesRequest
	7, // 2: orchestrator.public.v1.ReportContainersRequest.containers:type_name -> orchestrator.public.v1.Container
	5, // 3: orchestrator.public.v1.OrchestratorPublic.CreateNode:input_type -> orchestrator.public.v1.CreateNodeRequest
	0, // 4: orchestrator.public.v1.OrchestratorPublic.GetNodes:input_type -> orchestrator.public.v1.GetNodesRequest
	3, // 5: orchestrator.public.v1.OrchestratorPublic.Ping:input_type -> orchestrator.public.v1.PingRequest
	8, // 6: orchestrator.public.v1.OrchestratorPublic.ReportContainers:input_type -> orchestrator.public.v1.ReportContainersRequest
	6, // 7: orchestrator.public.v1.OrchestratorPublic.CreateNode:output_type -> orchestrator.public.v1.CreateNodeResponse
	1, // 8: orchestrator.public.v1.OrchestratorPublic.GetNodes:output_type -> orchestrator.public.v1.GetNodesResponse
	4, // 9: orchestrator.public.v1.OrchestratorPublic.Ping:output_type -> orchestrator.public.v1.PingResponse
	9, // 10: orchestrator.public.v1.OrchestratorPublic.ReportContainers:output_type -> orchestrator.public.v1.ReportContainersResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orchestrator_public_proto_init() }
func file_orchestrator_public_proto_init() {
	if File_orchestrator_public_proto != nil {
		return
	}
	file_orchestrator_public_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_public_proto_rawDesc), len(file_orchestrator_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_public_proto_goTypes,
		DependencyIndexes: file_orchestrator_public_proto_depIdxs,
		MessageInfos:      file_orchestrator_public_proto_msgTypes,
	}.Build()
	File_orchestrator_public_proto = out.File
	file_orchestrator_public_proto_goTypes = nil
	file_orchestrator_public_proto_depIdxs = nil
}
