// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: orchestrator_public.proto

package grpc_public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorPublic_CreateNode_FullMethodName       = "/orchestrator.public.v1.OrchestratorPublic/CreateNode"
	OrchestratorPublic_GetNodes_FullMethodName         = "/orchestrator.public.v1.OrchestratorPublic/GetNodes"
	OrchestratorPublic_Ping_FullMethodName             = "/orchestrator.public.v1.OrchestratorPublic/Ping"
	OrchestratorPublic_ReportContainers_FullMethodName = "/orchestrator.public.v1.OrchestratorPublic/ReportContainers"
)

// OrchestratorPublicClient is the client API for OrchestratorPublic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorPublic is the agent-facing gRPC service, served over TCP.
type OrchestratorPublicClient interface {
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	ReportContainers(ctx context.Context, in *ReportContainersRequest, opts ...grpc.CallOption) (*ReportContainersResponse, error)
}

type orchestratorPublicClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorPublicClient(cc grpc.ClientConnInterface) OrchestratorPublicClient {
	return &orchestratorPublicClient{cc}
}

func (c *orchestratorPublicClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, OrchestratorPublic_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPublicClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, OrchestratorPublic_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPublicClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, OrchestratorPublic_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorPublicClient) ReportContainers(ctx context.Context, in *ReportContainersRequest, opts ...grpc.CallOption) (*ReportContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportContainersResponse)
	err := c.cc.Invoke(ctx, OrchestratorPublic_ReportContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorPublicServer is the server API for OrchestratorPublic service.
// All implementations must embed UnimplementedOrchestratorPublicServer
// for forward compatibility.
//
// OrchestratorPublic is the agent-facing gRPC service, served over TCP.
type OrchestratorPublicServer interface {
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	ReportContainers(context.Context, *ReportContainersRequest) (*ReportContainersResponse, error)
	mustEmbedUnimplementedOrchestratorPublicServer()
}

// UnimplementedOrchestratorPublicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorPublicServer struct{}

func (UnimplementedOrchestratorPublicServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedOrchestratorPublicServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedOrchestratorPublicServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOrchestratorPublicServer) ReportContainers(context.Context, *ReportContainersRequest) (*ReportContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportContainers not implemented")
}
func (UnimplementedOrchestratorPublicServer) mustEmbedUnimplementedOrchestratorPublicServer() {}
func (UnimplementedOrchestratorPublicServer) testEmbeddedByValue()                            {}

// UnsafeOrchestratorPublicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorPublicServer will
// result in compilation errors.
type UnsafeOrchestratorPublicServer interface {
	mustEmbedUnimplementedOrchestratorPublicServer()
}

func RegisterOrchestratorPublicServer(s grpc.ServiceRegistrar, srv OrchestratorPublicServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorPublicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorPublic_ServiceDesc, srv)
}

func _OrchestratorPublic_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPublicServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPublic_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPublicServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPublic_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPublicServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPublic_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPublicServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPublic_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPublicServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPublic_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPublicServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorPublic_ReportContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorPublicServer).ReportContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorPublic_ReportContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorPublicServer).ReportContainers(ctx, req.(*ReportContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorPublic_ServiceDesc is the grpc.ServiceDesc for OrchestratorPublic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorPublic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.public.v1.OrchestratorPublic",
	HandlerType: (*OrchestratorPublicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _OrchestratorPublic_CreateNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _OrchestratorPublic_GetNodes_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _OrchestratorPublic_Ping_Handler,
		},
		{
			MethodName: "ReportContainers",
			Handler:    _OrchestratorPublic_ReportContainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator_public.proto",
}
